include:
  - project: 'antwerpen/across/across-development'
    file:
      - '/gitlab-ci/docker.gitlab-ci.yml'
      - '/gitlab-ci/common.gitlab-ci.yml'
      - '/gitlab-ci/unit-tests.gitlab-ci.yml'
      - '/gitlab-ci/unit-tests-docker.gitlab-ci.yml'
      - '/gitlab-ci/integration-tests-docker.gitlab-ci.yml'
      - '/gitlab-ci/deploy.gitlab-ci.yml'

variables:
  ACROSS_FRAMEWORK_VERSION: 5.5-SNAPSHOT
  ACROSS_AUTOCONFIGURE_VERSION: 2.5-SNAPSHOT
  ACROSS_BASE_MODULES_VERSION: 4.5-SNAPSHOT
  ACROSS_ENTITY_ADMIN_MODULES_VERSION: 4.5-SNAPSHOT
  ACROSS_USER_AUTH_MODULES_VERSION: 4.5-SNAPSHOT
  REVISION: 6.5-SNAPSHOT
  NODEJS_DOCKER_IMAGE_VERSION: 10

.frontend:
  stage: test
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/node:${NODEJS_DOCKER_IMAGE_VERSION}
  script:
    - cd ${FRONTEND_DIR}
    - yarn install
    #- yarn build:prod
    - ./node_modules/gulp/bin/gulp.js scss js --production

frontend:file-manager-module:
  extends:
    - .frontend
  variables:
    FRONTEND_DIR: file-manager-module/src/main/frontend
  artifacts:
    paths:
      - file-manager-module/src/main/resources/views/static/FileManagerModule/

.verify:
  before_script:
    - if [[ -f ci-before.sh ]]; then ./ci-before.sh; fi
    - git diff
    - apt-get update
    - apt-get install -y ghostscript graphicsmagick # docker.io
    #- docker login -u $CI_DEPENDENCY_PROXY_USER -p $CI_DEPENDENCY_PROXY_PASSWORD $CI_DEPENDENCY_PROXY_SERVER

.itest:
  before_script:
    - if [[ -f ci-before.sh ]]; then ./ci-before.sh; fi
    - git diff
    - apt-get update
    - apt-get install -y ghostscript graphicsmagick # docker.io
    #- docker login -u $CI_DEPENDENCY_PROXY_USER -p $CI_DEPENDENCY_PROXY_PASSWORD $CI_DEPENDENCY_PROXY_SERVER
