[[WebCmsPage-overview]]
==== Page model
===== WebCmsPage
A `WebCmsPage` represents a single page in the cms. It has an association with a `WebCmsPageType` which contains sensible defaults.

==== Properties
.Properties of a menu
[options="header", cols="2,1,1,3,1"]
|================
|Name|Type|Mandatory|Description|Default Value
|Page Type|Page Type|Yes|Defines the page type of a page. Can be set during create but not altered afterwards.|Default
|Title|String|Yes|The title of the page.|None
|Parent|Select|No|Parentpage of the page.|None
|Template|String|No|The thymeleaf template of the page. The filename of the page without the extension.|None
|Path Segment|String|No|A description of the menu.|None
|Canonical Path|String|No|A description of the menu.|None
|Published|String|No|A description of the menu.|None
|Publication Date|String|No|A description of the menu.|None
|Auto create menu items|String|No|A description of the menu.|None
|================

There are two configurable subsections, one for URL settings and one for publication settings

.URL settings
|===
|Field|Required|Type|Description|Default Value
|Path Segment|Yes|String|Path (URL) of the page.|None
|Canonical path|Yes|String|FQDN of the page.|None
|===

.Publish settings
|===
|Field|Required|Type|Description|Default Value
|Published|Yes|Boolean|If the page is published (or not). Published pages are visible for regular users.|None
|Publication Date|No|Date|The page is only visible if the access date of the file is greater than the publication date.|None
|Auto-create new menu items|Yes|Boolean|If checked, creates a new menu item after creation.|False
|===

When creating or updating the page, the following updates are done with regards to the associated URLs:

* If the page object is saved, and the publication is in the future or not yet published, update the primary url.
* If the page object is saved and published but the publication date is in the past, no adjustments to the primary url will happen.


[[WebCmsPageType-overview]]
===== WebCmsPageType

A WebCmsPageType is used for assigning a certain type of page to a <<WebCmsPage-overview, WebCmsPage>>. The default page type is controlled via the `webCmsModule.pages.default-page-type` parameter.

.Parameters
|===
|Field|Required|Type|Description|Default Value
|Name|Yes|String|The name of the page type. Displayed in the drop down list when creating a new page.|None
|Attributes|No|<<WebCmsPageType-attributes, Attributes>>|The attributes affecting the behaviour when rendering/creating the page. Specified as key-value pairs.|None
|wcm:components|No|Components|The components that are automatically generated when creating a page that uses this page type.|None
|===

.Attributes[[WebCmsPageType-attributes]]
|===
|Attribute|Description
|contentTemplate|The identifier of the selector in the thymeleaf page that contains the actual page content.
|defaultTemplate|The thymeleaf page that is used if there has not been a page specified on the page itself.
|hasEndpoint|Whether or not an endpoint is defined for a page. If you disable this, the menu and URL functionality will be disabled on the front end.
|isPublishable|Whether or not the page can be published.
|===


===== Importing a page type
In the standard setup one can only manipulate the available page types via the import functionality. The default types are described further down. One can extrapolate any other needed page type from them

.Default page types
[source,yaml,indent=0]
----
types:
  page:
    default: //<1>
      name: Default
    template:
      name: Template
      attributes: //<2>
        hasEndpoint: false
        isPublishable: false
----
<1> The default page type. Notice that nothing
<2> <<WebCmsPageType-attributes, Attributes>> are defined as simple key-value pairs.


===== Importing a page
One can import a page by using the import infrastructure provided by the import functionality of WebCMS.

.Example page
[source,yaml,indent=0]
----
page:
  - title: Always Created Page //<1>

  - objectId: "wcm:asset:page:reference-simple"
    title: Simple Page

  - objectId: "wcm:asset:page:reference-simple-child"
    title: Simple Child Page
    parent: "wcm:asset:page:reference-simple" // <2>
    published: true

  - objectId: "wcm:asset:page:reference-fixed-path-segment"
    title: Fixed Path Segment Page
    parent: /simple-page // <2>
    pathSegment: fixed
    publicationDate: "2017-03-14"

  - objectId: "wcm:asset:page:reference-faq"
    title: Frequently Asked Questions
    pathSegment: faq
    wcm:menu-items: // <3>
      - menu: sideNav
      - menu: topNav
        title: FAQ
        path: /help/faq
        sortIndex: 10
----
<1> Sensible defaults are used. Only title is mandatory.
<2> One can refer to both the object id and the canonical path.
<3> You can use this notation to manipulate the associated menu items.

.Page properties that can be imported
[options="header", cols="1,1,2"]
|================
|Property|On UI|Details
|title|Title|
|parent|Parent|Should be the canonical path or the objectId
|pathSegment|Path segment|
|pathSegmentGenerated|Generate path segment based on title|
|canonicalPath|Canonical Path|
|canonicalPathGenerated|Generate canonical path based on title|
|template|Template|
|pageType|Page type|
|objectId|-|
|isPublished|Published|
|publicationDate|Publication Date|
|wcm:menu-items|For menu manipulation
|================