[[importing-data]]
== Importing data

One can import data by combining yml files with an installer.

=== WebCmsDataImportService
Import data from `Map` structures directly from code.
It is strongly advised to provide a `UnitOfWorkFactory` bean in your application.
If one is present, a data import will execute as a single unit of work.

NOTE: The default implementation requires either a `UnifOfWorkFactory` to be present or your import to run within a single transaction to enable lazy initialisation of all default entities.

=== Creating the installer
An installer for installing data in yml files should implement the `AbstractWebCmsDataInstaller`.

=== Yaml structure
The classes responsible for the imports will look at the following fields in the yml file:

[cols="1, 3"]
|===
|wcm:action|Describes the <<importing-action, action>> that should be done on the item.
|(fieldname)|When importing will set the property of the object being imported to the value specified in the yml file.
If the field is not present in the file, the property will be set to the default value (if working with a new object)
or the value will not be altered (if working with an existing object)
|===

[[importing-action]]
=== Actions
If the parent contains a wcm:action and the child doesn't, the child action is the same as the parent one.
if no wcm:action is specified, the value is `create-update`.

[cols="1,3"]
|===
|create|
|update|Update any existing data.
|delete|
|replace|If the item exists, overwrite it with the new data (i.e. replace the existing object, but keep the primary key)
|===
- create
- update
- create-update
- delete
- replace

For more information regarding the importing of pages, please refer to <<WebCmsPage-import, the relevant chapter>>.

For more information regarding the importing of menus, please refer to <<WebCmsMenu-import, the relevant chapter>>. For adding menu items to pages, please refer to the chapter on
importing <<WebCmsPage-import, pages>>.