= WebCmsModule
Arne Vandamme
0.0.2-SNAPSHOT
:toc: left
:sectanchors:
:module-version: 0.0.2-SNAPSHOT
:module-name: WebCmsModule
:module-artifact: web-cms-module
:module-url: https://foreach.atlassian.net/wiki/display/AX/WebCmsModule
:application-info-url: https://foreach.atlassian.net/wiki/display/AX/ApplicationInfoModule
:spring-security-module-url: https://foreach.atlassian.net/wiki/display/AX/SpringSecurityModule
:entity-module-url: https://foreach.atlassian.net/wiki/display/AX/EntityModule

[copyright,verbatim]
--
Copyright (C) 2014-2017 +
[small]#Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.#
--

[abstract]
== About
The {module-name} provides infrastructure for basic web CMS features.
Most important part is that it allows managing web pages using an administration UI.

Module website: {module-url}

:numbered:
== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across.modules</groupId>
			<artifactId>{module-artifact}</artifactId>
			<version>{module-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

{module-name} only has a required dependency on AcrossWebModule.

.Module dependencies
|===
|Module |Type |Description

|{entity-module-url}[EntityModule]
|optional
|In combination with `AdminWebModule` this enables the management forms in the administration UI.
|===

=== Module settings

All properties start with the *webCmsModule.* prefix.

|===
|Property |Type |Description |Default

|pages.default-template
|`String`
|Default template to use if no custom template specified on a page entity.
|`th/WebCmsModule/default-page-template`

|pages.template-prefix
|`String`
|Prefix to be added to relative template names.
This corresponds usually with the base directory where the (Thymeleaf) templates are located.
If unspecified the default resources of any present `@AcrossApplication` will be used.
|

|webCmsModule.default-data.assets.enabled
|
|Enable default assets to be added: this includes component and asset types as well as some sample assets.
|`true`

|===

== What's new in this version?
:numbered!:
=== 0.0.2-SNAPSHOT
Initial public release available on http://search.maven.org/[Maven central].

:numbered:
== How {module-name} works

annotate controller method with `WebCmsEndpointMapping`
Specify type of endpoint and Http status code(s) to listen to
body of method describes how to show endpoint

default `WebCmsPageEndpoint` puts page on model and uses default Thymeleaf template
default `WebCmsRemoteEndpoint` does redirect to target url

=== Create your own endpoint
Create an entity that extends `WebCmsEndpoint` which contains all properties needed to display the endpoint
Create a corresponding repository
Reference the endpoint and/or HTTP status code(s) in annotation of controller method
Handle your properties according how you want to display your endpoint.  If needed, provide a default Thymeleaf template.


WARNING: in case of problems, make sure that the request mapping is last

in case of a page, a default page will be rendered
a default webcmspagetemplate will be used if none is specified

specify a default template yourself
add a base location for the template files

== Domain model



=== WebCmsEndpoint

An endpoint can be anything that can be accessed by a collection or URLs.  The endpoint should contain all the data needed to display itself when accessing.

This module provides two endpoints, one for pages and one for redirects.  The first - `WebCmsPageEndpoint` - will reference the page and the urls for that page.
The latter - `WebCmsRemoteEndpoint` - has a collection of urls which should be redirected and contains the target url which url should be targeted.

A `WebCmsEndpoint` or one of its subclasses can be used as method parameter.

=== WebCmsUrl

URL targeting a specific endpoint and HTTP-status code.  A `WebCmsUrl` must be coupled with an `WebCmsEndpoint`.

//* path: url path
//* status code: http status code, will determine what will happen when the url is requested
//** 200 will serve the content
//** 3xx will perform a redirect to the canonical url
//** other status codes will serve the content but with the custom status code (eg custom 404 page)
//* is canonical: only one url for an endpoint can be the canonical url
//* endpoint: the endpoint target

A `WebCmsUrl` or one of its subclasses can be used as method parameter.

=== WebCmsPage

a generated path segment will be SEO friendly

* path segment: path (url) of the page - used for default menu
* path segment generated: true if the path segment is generated based on the title - a path segment is url friendly
* title: descriptive title of the page
* template: to render the page
* canonicalPath: fq path of the page - usually corresponds with the main url
* canonical path generated: true if the canonical path should be generated based on the parent hierarchy
* inheritable canonical path: true (default) if the canonical path should be used by children
* canonical url should match canonical path: if true the main url should equal the canonical path, if the path changes the main url will change
* parent: optional parent page
* hidden: if true the page itself cannot be requested (and might not have a url)
- its properties will still be inherited (eg path, layout, template) - in the default menu it will still insert a group section
* disabled: this page and all its children will not be rendered

default urls for assets
- primary url
- auto generated on save, updated as long as nog published or publication is in the future

WebCmsMenu

named menu, consisting of different items

WebCmsMenu item:
* path: in the menu tree
* title: of the item
* url: fixed url - if a page is linked and url is empty the page url will be used
* linkedPage: optional page this menu is linking to
* sortIndex: index of the item
* group: is the item group or not

when a BuildMenuEvent is published for a menu with that name, all items will be added

Generating a sitemap

=== Programmatically creating pages
you can use yaml to create pages

=== Default data

disable default data:
webCmsModule.default-data.assets.enabled = false

importing data using yaml (installer)

include::chap-web-components.adoc[]


== Publication model
Enabling urls for WebCmsAsset implementations: wire WebCmsAssetUrlConfiguration

WebCmsPublication
A publication has a specific type.
A publication has a set of possible article types that is a subset of the article types allowed on the publication type.

WebCmsPublicationType
Type of publication.
A publication type determines the possible article types allowed.

WebCmsArticle
An article requires a specific article type.

WebCmsArticleType

modifying the default components:

types:
  article:
    blog:
      wcm:components:
        bodyTemplate:
          wcm:components:
            main-image:
              componentType: image
              title: Image
              sortIndex: 0
            body:
              sortIndex: 1

== Performance

caches: WebCmsUrlCache
enable Hibernate 2nd level cache
webCmsModule.urls.included-path-patterns
webCmsModule.urls.excluded-path-patterns