= WebCmsModule
Arne Vandamme
0.0.2-SNAPSHOT
:toc: left
:sectanchors:
:module-version: 0.0.2-SNAPSHOT
:module-name: WebCmsModule
:module-artifact: web-cms-module
:module-url: https://foreach.atlassian.net/wiki/display/AX/WebCmsModule
:application-info-url: https://foreach.atlassian.net/wiki/display/AX/ApplicationInfoModule
:spring-security-module-url: https://foreach.atlassian.net/wiki/display/AX/SpringSecurityModule
:entity-module-url: https://foreach.atlassian.net/wiki/display/AX/EntityModule
:ehcache-module-url: https://foreach.atlassian.net/wiki/display/AX/EhcacheModule

[copyright,verbatim]
--
Copyright (C) 2014-2017 +
[small]#Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.#
--

[abstract]
== About
The {module-name} provides infrastructure for basic web CMS features.
Most important part is that it allows managing web pages using an administration UI.

Module website: {module-url}

:numbered:
// General information
include::chap-general-information.adoc[]

// What's new section
include::chap-whats-new.adoc[]

:numbered:
== How {module-name} works

annotate controller method with `WebCmsEndpointMapping`
Specify type of endpoint and Http status code(s) to listen to
body of method describes how to show endpoint

default `WebCmsPageEndpoint` puts page on model and uses default Thymeleaf template
default `WebCmsRemoteEndpoint` does redirect to target url

=== Create your own endpoint
Create an entity that extends `WebCmsEndpoint` which contains all properties needed to display the endpoint
Create a corresponding repository
Reference the endpoint and/or HTTP status code(s) in annotation of controller method
Handle your properties according how you want to display your endpoint.  If needed, provide a default Thymeleaf template.


WARNING: in case of problems, make sure that the request mapping is last

in case of a page, a default page will be rendered
a default webcmspagetemplate will be used if none is specified

specify a default template yourself
add a base location for the template files

// Domain model - bulk of domain documentation
include::chap-domain-model.adoc[]

// General data import information
include::importing/chap-importing-data.adoc[]

// Performance tuning related configuration
include::chap-performance-tuning.adoc[]

// Extending the domain model: creating your own assets, types, configuring admin UI etc
include::extending/chap-extending-domain-model.adoc[]

// Appendices
include::appendices/chap-appendices.adoc[]