= WebCmsModule
Arne Vandamme
0.0.1-SNAPSHOT
:toc: left
:sectanchors:
:module-version: 0.0.1-SNAPSHOT
:module-name: WebCmsModule
:module-artifact: web-cms-module
:module-url: https://foreach.atlassian.net/wiki/display/AX/WebCmsModule
:application-info-url: https://foreach.atlassian.net/wiki/display/AX/ApplicationInfoModule
:spring-security-module-url: https://foreach.atlassian.net/wiki/display/AX/SpringSecurityModule
:entity-module-url: https://foreach.atlassian.net/wiki/display/AX/EntityModule

[copyright,verbatim]
--
Copyright (C) 2014-2017 +
[small]#Copies of this document may be made for your own use and for distribution to others, provided that you do not charge any fee for such copies and further provided that each copy contains this Copyright Notice, whether distributed in print or electronically.#
--

[abstract]
== About
The {module-name} provides infrastructure for basic web CMS features.
Most important part is that it allows managing web pages using an administration UI.

Module website: {module-url}

:numbered:
== General information

=== Artifact
[source,xml,indent=0]
[subs="verbatim,quotes,attributes"]
----
	<dependencies>
		<dependency>
			<groupId>com.foreach.across.modules</groupId>
			<artifactId>{module-artifact}</artifactId>
			<version>{module-version}</version>
		</dependency>
	</dependencies>
----

=== Module dependencies

{module-name} only has a required dependency on AcrossWebModule.

.Module dependencies
|===
|Module |Type |Description

|{entity-module-url}[EntityModule]
|optional
|In combination with `AdminWebModule` this enables the management forms in the administration UI.
|===

=== Module settings

All properties start with the *webCmsModule.* prefix.

|===
|Property |Type |Description |Default

|pages.default-template
|`String`
|Default template to use if no custom template specified on a page entity.

|pages.template-prefix
|`String`
|Prefix to be added to relative template names.
This corresponds usually with the base directory where the (Thymeleaf) templates are located.
If unspecified the default resources of any present `@AcrossApplication` will be used.

|webCmsModule.default-data.assets.enabled
|
|Disable default assets data.

|===

== What's new in this version?
:numbered!:
=== 0.0.1-SNAPSHOT
Initial public release available on http://search.maven.org/[Maven central].

:numbered:
== How {module-name} works

will install a default controller
all other request mappings will take precedence
no specific mapping, an endpoint request will be done
no endpoint found a 404 will be thrown
else the typed endpoint handler will be called

WARNING: in case of problems, make sure that the request mapping is last

in case of a page, a default page will be rendered
a default webcmspagetemplate will be used if none is specified

specify a default template yourself
add a base location for the template files

== Domain model

WebCmsEndpoint

target for one or more endpoint urls

WebCmsEndpointUrl

URL targeting a specific endpoint

* path: url path
* status code: http status code, will determine what will happen when the url is requested
** 200 will serve the content
** 3xx will perform a redirect to the canonical url
** other status codes will serve the content but with the custom status code (eg custom 404 page)
* is canonical: only one url for an endpoint can be the canonical url
* endpoint: the endpoint target

WebCmsPage

a generated path segment will be SEO friendly

* path segment: path (url) of the page - used for default menu
* path segment generated: true if the path segment is generated based on the title - a path segment is url friendly
* title: descriptive title of the page
* template: to render the page
* canonicalPath: fq path of the page - usually corresponds with the main url
* canonical path generated: true if the canonical path should be generated based on the parent hierarchy
* inheritable canonical path: true (default) if the canonical path should be used by children
* canonical url should match canonical path: if true the main url should equal the canonical path, if the path changes the main url will change
* parent: optional parent page
* hidden: if true the page itself cannot be requested (and might not have a url)
- its properties will still be inherited (eg path, layout, template) - in the default menu it will still insert a group section
* disabled: this page and all its children will not be rendered

WebCmsMenu

named menu, consisting of different items

WebCmsMenu item:
* path: in the menu tree
* title: of the item
* url: fixed url - if a page is linked and url is empty the page url will be used
* linkedPage: optional page this menu is linking to
* sortIndex: index of the item
* group: is the item group or not

when a BuildMenuEvent is published for a menu with that name, all items will be added

Generating a sitemap

=== Programmatically creating pages
you can use yaml to create pages

=== Default data

disable default data:
webCmsModule.default-data.assets.enabled = false