=== Endpoints and URLs

==== WebCmsEndpoint

An endpoint can be anything that can be accessed by a collection or URLs.  The endpoint should contain all the data needed to display itself when accessing.

This module provides two endpoints, one for pages and one for redirects.  The first - `WebCmsPageEndpoint` - will reference the page and the urls for that page.
The latter - `WebCmsRemoteEndpoint` - has a collection of urls which should be redirected and contains the target url which url should be targeted.

A `WebCmsEndpoint` or one of its subclasses can be used as method parameter.

[[WebCmsUrl-overview]]
==== WebCmsUrl

URL targeting a specific endpoint and HTTP-status code.  A `WebCmsUrl` must be coupled with an `WebCmsEndpoint`.

[[WebCmsUrl-pages]]
.Properties of an URL (for pages)
[options="header", cols="2,1,1,3,1"]
|================
|Name|Type|Mandatory|Description|Default Value
|Path|String|Yes|The relative path of the URL|None
|Http Status|Http Status|The status that will be thrown. See the next table for more information.|None
|Is Primary URL|Boolean|Is this the primary URL? Must be unique per page|None
|================

.HTTP Status
[options="header", cols="1,1,2"]
|================
|Status|Corresponds With|Result
|Moved Permanently|301|Redirects to the primary URL
|Moved Temporarily|302|Redirects to the primary URL
|Not Found|404|Redirects to the 404 page.
|OK|200|Done
|================

//* path: url path
//* status code: http status code, will determine what will happen when the url is requested
//** 200 will serve the content
//** 3xx will perform a redirect to the canonical url
//** other status codes will serve the content but with the custom status code (eg custom 404 page)
//* is canonical: only one url for an endpoint can be the canonical url
//* endpoint: the endpoint target

A `WebCmsUrl` or one of its subclasses can be used as method parameter.

`WebCmsUrls` can be cached when you specify a `CacheManger` and a cache with name *pathToWebCmsUrlCache*.
{ehcache-module-url}[EhcacheModule] should be used to provide a `CacheManager`.  The caching of `WebCmsUrl` is recommended
because it is queries a lot when resolving a `WebCmsEndpointContext`.